apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: blogpage-weighted
spec:
  destination:
    name: blogpage
  precedence: 2
  route:
  - labels:
      version: v1
    weight: 80
  - labels:
      version: v2
    weight: 20
